name: Upload Data - Cron


on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  upload-data:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install requirements
      run: |
        pip install --upgrade --upgrade-strategy eager -r requirements.txt -e .

    - name: Run - Upload Data
      run: |
        export PYTHONPATH="$PYTHONPATH:./src"
        python src/palk/pipeline.py

    - name: Checkout repo branch 'data'
      uses: actions/checkout@v2
      with:
        ref: 'data'
        token: "${{ secrets.REPO_DATA_TOKEN }}"

    - name: Copy data and push
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        cp -r /tmp/palk.* .
        cp /tmp/README.md .
        git add .
        git commit -m "Updated data $(date)"
        git push origin data
